# -*- coding: utf-8 -*-
"""Codegenie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQssGTsZPtK52UDQl5q0vjvUD0fPXm97
"""

#CodeGenie: AI-Powered Code Generation using CodeLlama
import google.generativeai as genai
import os

# Configure API key
API_KEY = "AIzaSyDOL1y16Ls6i_Psn5kLYHefdjCEFcU5Gvs"
genai.configure(api_key=API_KEY)

# Function to generate code with explanations and debugging suggestions
def generate_code(prompt):
    model = genai.GenerativeModel("gemini-pro")
    response = model.generate_content(prompt + " Provide step-by-step explanations and debugging suggestions.")
    return response.text if response.text else "Error: No response received."

# User input for code generation
user_prompt = input("Enter your code requirement: ")
generated_code = generate_code(user_prompt)

# Save generated code to a file
with open("generated_code.py", "w") as file:
    file.write(generated_code)

print("\nGenerated Code with Explanations:\n")
print(generated_code)
print("\nCode saved to 'generated_code.py'")